version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=dev
      - DB_NAME=food_app
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /api/src/

  mysql:
    build:
      context: ./mysql/
      dockerfile: dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=dev

networks:
  internal:

volumes:
  dev: