FROM node:13
WORKDIR /api
SHELL ["bash", "-ec"]

COPY ./src/ ./src/

# Copy src and configuration files.
COPY ./makefile /api/makefile
COPY ./package.json /api/package.json
COPY ./tsconfig.json /api/tsconfig.json
COPY ./run /api/run

COPY ./recipes.json /api/recipes.json

# Install dependencies.
RUN make node_modules/;
RUN make compile;

CMD node bin/server.js;